# Generated by Django 5.0.6 on 2026-03-16 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Módulo por Empresa',
                'verbose_name_plural': 'Módulos por Empresa',
                'db_table': 'modulos_empresa_modulo',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.SlugField(help_text="Used in modulo_requerido. e.g. 'clientes', 'ventas'.", unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('plan_minimo', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', help_text='Minimum plan required to access this module.', max_length=20)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Display order in navigation.')),
                ('activo_en_plataforma', models.BooleanField(default=True, help_text='Master switch. False = disabled for all empresas.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modulos_modulo',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
