# Generated by Django 5.0.6 on 2026-03-16 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('modulos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresamodulo',
            name='activado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresamodulo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_activos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='empresamodulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='modulos.modulo'),
        ),
        migrations.AddIndex(
            model_name='empresamodulo',
            index=models.Index(fields=['empresa', 'activo'], name='modulos_emp_empresa_5ab5d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empresamodulo',
            unique_together={('empresa', 'modulo')},
        ),
    ]
