# Generated by Django 5.0.6 on 2026-03-16 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', help_text="Hex color code for UI display, e.g. '#3B82F6'.", max_length=7)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text="Display order within the empresa's category list.")),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'db_table': 'inventario_categoria_producto',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada de stock'), ('SALIDA', 'Salida por venta'), ('AJUSTE_POSITIVO', 'Ajuste positivo (conteo físico)'), ('AJUSTE_NEGATIVO', 'Ajuste negativo (conteo físico)'), ('DEVOLUCION', 'Devolución de cliente'), ('MERMA', 'Merma (daño / vencimiento / robo)')], help_text='Accounting type — determines whether cantidad adds or subtracts.', max_length=30)),
                ('cantidad', models.PositiveIntegerField(help_text='Units moved. Always strictly positive (Invariant I5). Sign is determined by TipoMovimiento, not by this field.')),
                ('stock_anterior', models.IntegerField(help_text='Snapshot of Producto.stock_actual BEFORE this movement.')),
                ('stock_resultante', models.IntegerField(help_text='Snapshot of Producto.stock_actual AFTER this movement. Must equal stock_anterior ± cantidad (Invariant I4).')),
                ('referencia_tipo', models.CharField(blank=True, help_text="Type of originating object, e.g. 'venta', 'orden_compra', 'ajuste_manual'. Pair with referencia_id for cross-module traceability.", max_length=50)),
                ('referencia_id', models.UUIDField(blank=True, help_text='UUID of the originating object (venta.id, orden_compra.id, etc.).', null=True)),
                ('motivo', models.TextField(blank=True, help_text='Human-readable reason for the movement.')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at the time of movement. Used for inventory valuation in Reportes. NULL if not applicable.', max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'db_table': 'inventario_movimiento_stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al proveedor'), ('RECIBIDA_PARCIAL', 'Recibida parcialmente'), ('RECIBIDA_COMPLETA', 'Recibida completamente'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=30)),
                ('numero', models.CharField(blank=True, help_text='Optional internal PO number for reference.', max_length=50)),
                ('fecha_emision', models.DateField(help_text='Date the order was created.')),
                ('fecha_esperada', models.DateField(blank=True, help_text='Expected delivery date.', null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, help_text='Actual first reception timestamp (set on first recibir_orden call).', null=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'db_table': 'inventario_orden_compra',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('cantidad_pedida', models.PositiveIntegerField(help_text='Units ordered from the vendor.')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, help_text='Units received so far. Updated by recibir_orden().')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed cost per unit. Passed to MovimientoStock.costo_unitario on reception.', max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Órdenes de Compra',
                'db_table': 'inventario_orden_compra_detalle',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(help_text='Full product name as shown in UI and reports.', max_length=200)),
                ('codigo', models.CharField(blank=True, help_text='SKU, barcode, or internal reference code. Unique per empresa.', max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase cost per unit. Used for inventory valuation.', max_digits=12, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, help_text='Suggested sale price per unit. VentaService may use this as a default — actual price is on DetalleVenta.', max_digits=12, null=True)),
                ('stock_actual', models.IntegerField(default=0, help_text='Denormalized cache of Σ MovimientoStock. NEVER update directly. Always use MovimientoService.')),
                ('stock_minimo', models.IntegerField(default=0, help_text='Reorder threshold. When stock_actual <= stock_minimo, the product appears in the low-stock alert list.')),
                ('stock_maximo', models.IntegerField(blank=True, help_text='Optional upper bound. When stock_actual >= stock_maximo, the product appears in the overstock alert list.', null=True)),
                ('unidad_medida', models.CharField(default='unidades', help_text="Display label for the stock unit, e.g. 'kg', 'litros', 'unidades'.", max_length=50)),
                ('permite_stock_negativo', models.BooleanField(default=False, help_text='If True, stock_actual may go below zero (backorder / presale). If False, MovimientoService raises StockInsuficienteError on oversell.')),
                ('activo', models.BooleanField(default=True, help_text='Inactive products are hidden from sale and booking flows.')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'inventario_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.CharField(blank=True, help_text='CUIT/CUIL or equivalent tax identifier.', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True, help_text='Inactive vendors do not appear in the new-order flow.')),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'inventario_proveedor',
                'ordering': ['nombre'],
            },
        ),
    ]
