# Generated by Django 5.0.6 on 2026-03-09 14:41

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproducto',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.ordencompra'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Optional category for filtering and reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(help_text='The product whose stock changed.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(help_text='Vendor receiving this purchase order.', on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventario.proveedor'),
        ),
        migrations.AddIndex(
            model_name='categoriaproducto',
            index=models.Index(fields=['empresa', 'orden', 'nombre'], name='idx_categoria_empresa_orden'),
        ),
        migrations.AddConstraint(
            model_name='categoriaproducto',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'nombre'), name='unique_categoria_nombre_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'activo', 'nombre'], name='idx_producto_empresa_activo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'stock_actual'], name='idx_producto_empresa_stock'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'categoria', 'activo'], name='idx_producto_empresa_categoria'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'codigo'], name='idx_producto_empresa_codigo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(check=models.Q(('permite_stock_negativo', True), ('stock_actual__gte', 0), _connector='OR'), name='check_producto_stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(check=models.Q(('stock_minimo__gte', 0)), name='check_producto_stock_minimo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(check=models.Q(('stock_maximo__isnull', True), ('stock_maximo__gte', models.F('stock_minimo')), _connector='OR'), name='check_producto_stock_maximo_gte_minimo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo__gt', ''), ('deleted_at__isnull', True)), fields=('empresa', 'codigo'), name='unique_producto_codigo_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalle',
            index=models.Index(fields=['orden', 'producto'], name='idx_detalle_orden_producto'),
        ),
        migrations.AddIndex(
            model_name='ordencompradetalle',
            index=models.Index(fields=['empresa', 'producto'], name='idx_detalle_empresa_producto'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_pedida__gt', 0)), name='check_detalle_cantidad_pedida_positiva'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_recibida__lte', models.F('cantidad_pedida'))), name='check_detalle_recibida_lte_pedida'),
        ),
        migrations.AddConstraint(
            model_name='ordencompradetalle',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('orden', 'producto'), name='unique_detalle_producto_por_orden'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['empresa', 'producto', '-created_at'], name='idx_mov_emp_prod_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['empresa', 'tipo', '-created_at'], name='idx_movimiento_empresa_tipo'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['empresa', 'referencia_tipo', 'referencia_id'], name='idx_mov_emp_ref'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='check_movimiento_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(check=models.Q(('stock_resultante__gte', django.db.models.expressions.CombinedExpression(models.F('stock_anterior'), '-', models.F('cantidad'))), ('stock_resultante__lte', django.db.models.expressions.CombinedExpression(models.F('stock_anterior'), '+', models.F('cantidad')))), name='check_movimiento_stock_resultante_coherente'),
        ),
        migrations.AddConstraint(
            model_name='movimientostock',
            constraint=models.CheckConstraint(check=models.Q(('referencia_id__isnull', True), ('referencia_tipo__gt', ''), _connector='OR'), name='check_movimiento_referencia_tipo_requerido'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', 'activo', 'nombre'], name='idx_proveedor_empresa_activo'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'estado', '-fecha_emision'], name='idx_orden_empresa_estado'),
        ),
        migrations.AddIndex(
            model_name='ordencompra',
            index=models.Index(fields=['empresa', 'proveedor', '-fecha_emision'], name='idx_orden_empresa_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='ordencompra',
            constraint=models.CheckConstraint(check=models.Q(('fecha_esperada__isnull', True), ('fecha_esperada__gte', models.F('fecha_emision')), _connector='OR'), name='check_orden_fecha_esperada_gte_emision'),
        ),
    ]
