# Generated by Django 5.0.6 on 2026-03-16 17:19

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        ('inventario', '0001_initial'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(help_text="Display name, e.g. 'Efectivo', 'Tarjeta Visa', 'QR Mercado Pago'.", max_length=100)),
                ('tipo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta (crédito / débito)'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('QR', 'Pago QR (Mercado Pago, etc.)'), ('CUENTA', 'Cuenta corriente / crédito'), ('OTRO', 'Otro')], default='OTRO', help_text='Broad category for reporting and business logic.', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Inactive methods are hidden from the payment selection UI.')),
                ('acepta_vuelto', models.BooleanField(default=False, help_text='If True, the POS UI prompts for tendered amount and calculates change. Typically True only for EFECTIVO methods.')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Display order in payment selection UI.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'ventas_metodo_pago',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SecuenciaVenta',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0, help_text='Last used correlative number. Increment via VentaService._siguiente_numero() only.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secuencia de Venta',
                'verbose_name_plural': 'Secuencias de Venta',
                'db_table': 'ventas_secuencia_venta',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('numero', models.CharField(blank=True, help_text="Correlative reference number, e.g. 'V-2025-0001'. Set by VentaService.", max_length=20, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada'), ('DEVUELTA', 'Devuelta')], default='BORRADOR', max_length=15)),
                ('fecha', models.DateTimeField(help_text='Date and time of the sale (set at creation, not at confirmation).')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Σ LineaVenta.subtotal. Computed by VentaService. Never set manually.', max_digits=14)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, help_text='Sale-level discount applied after line subtotals.', max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='subtotal - descuento_total. Computed by VentaService. Never set manually.', max_digits=14)),
                ('pago_diferido', models.BooleanField(default=False, help_text='If True, full payment is not required at confirmation. Enables credit/account sales.')),
                ('datos_cliente', models.JSONField(blank=True, default=dict, help_text='Snapshot of client billing data at sale time. Readable even if the Cliente FK is later deleted. Used by facturacion module for invoice recipient.')),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Client who made the purchase. NULL for anonymous sales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('turno', models.ForeignKey(blank=True, help_text='Appointment that originated this sale. NULL for direct sales not linked to a turno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='turnos.turno')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas_venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Amount paid via this method.', max_digits=14)),
                ('referencia', models.CharField(blank=True, help_text='Payment provider reference: approval code, transfer ID, QR token, etc. Optional — not all methods produce a traceable reference.', max_length=100)),
                ('fecha', models.DateTimeField(help_text='Timestamp when this payment was registered.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('metodo_pago', models.ForeignKey(help_text='Payment method used for this payment record.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='ventas.metodopago')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Venta',
                'db_table': 'ventas_pago_venta',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='LineaVenta',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('descripcion', models.CharField(help_text='Product or service name at sale time. Always required. Auto-populated from producto.nombre when producto is set. Immutable after Venta.CONFIRMADA.', max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Unit price at sale time. Auto-populated from producto.precio_venta. Can be overridden by staff before confirmation. Immutable after Venta.CONFIRMADA.', max_digits=12)),
                ('cantidad', models.PositiveIntegerField(help_text='Units sold. Immutable after Venta.CONFIRMADA.')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Line-level discount amount (not percentage). Applied before subtotal.', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='(precio_unitario × cantidad) - descuento. Computed by VentaService. Never set manually.', max_digits=14)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Display order of this line within the sale. Preserved on receipts, invoices, and the UI. Assigned by VentaService as len(existing_lineas) at insertion time.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('movimiento_stock', models.ForeignKey(blank=True, help_text='The MovimientoStock(SALIDA) created for this line at confirmation. NULL for service lines (no stock movement) and for BORRADOR sales. SET_NULL: losing the link does not invalidate the sale record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_venta', to='inventario.movimientostock')),
                ('producto', models.ForeignKey(blank=True, help_text='Product sold. NULL for services or ad-hoc charges with no inventory. PROTECT: products with sales history cannot be deleted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_venta', to='inventario.producto')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Línea de Venta',
                'verbose_name_plural': 'Líneas de Venta',
                'db_table': 'ventas_linea_venta',
                'ordering': ['venta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionVenta',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('motivo', models.TextField(help_text='Reason for the return. Required for audit trail.')),
                ('total_devuelto', models.DecimalField(decimal_places=2, default=0, help_text='Σ DevolucionLineaVenta.monto_devuelto. Computed by VentaService. Used for refund reconciliation.', max_digits=14)),
                ('fecha', models.DateTimeField(help_text='Timestamp when the return was registered.')),
                ('notas', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(help_text='The sale being returned against. PROTECT: devoluciones cannot be orphaned by sale deletion.', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Devolución de Venta',
                'verbose_name_plural': 'Devoluciones de Venta',
                'db_table': 'ventas_devolucion_venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionLineaVenta',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('cantidad_devuelta', models.PositiveIntegerField(help_text='Units being returned. Must be <= linea_venta.cantidad - already_returned. Enforced by VentaService before creation.')),
                ('monto_devuelto', models.DecimalField(decimal_places=2, help_text='linea_venta.precio_unitario × cantidad_devuelta. Uses the snapshot price from the original line.', max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('movimiento_stock', models.ForeignKey(blank=True, help_text='The MovimientoStock(DEVOLUCION) for this returned line. NULL for service lines with no inventory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_linea', to='inventario.movimientostock')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='ventas.devolucionventa')),
                ('linea_venta', models.ForeignKey(help_text='The original sale line being returned.', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='ventas.lineaventa')),
            ],
            options={
                'verbose_name': 'Línea de Devolución',
                'verbose_name_plural': 'Líneas de Devolución',
                'db_table': 'ventas_devolucion_linea_venta',
                'indexes': [models.Index(fields=['devolucion'], name='idx_devlin_dev'), models.Index(fields=['linea_venta'], name='idx_devlin_lin_vta')],
            },
        ),
        migrations.AddConstraint(
            model_name='devolucionlineaventa',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_devuelta__gt', 0)), name='check_devolucion_linea_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='devolucionlineaventa',
            constraint=models.CheckConstraint(check=models.Q(('monto_devuelto__gte', 0)), name='check_devolucion_linea_monto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='devolucionlineaventa',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('devolucion', 'linea_venta'), name='unique_devolucion_linea_por_devolucion'),
        ),
        migrations.AddIndex(
            model_name='metodopago',
            index=models.Index(fields=['empresa', 'activo', 'orden'], name='idx_metodo_pago_empresa_activo'),
        ),
        migrations.AddConstraint(
            model_name='metodopago',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'nombre'), name='unique_metodo_pago_nombre_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='secuenciaventa',
            constraint=models.UniqueConstraint(fields=('empresa',), name='unique_secuencia_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'estado'], name='idx_venta_empresa_estado'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'fecha'], name='idx_venta_empresa_fecha'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'numero'], name='idx_venta_empresa_numero'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'cliente', 'fecha'], name='idx_venta_empresa_cliente'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['empresa', 'estado', 'fecha'], name='idx_venta_empresa_estado_fecha'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='check_venta_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.CheckConstraint(check=models.Q(('descuento_total__lte', models.F('subtotal'))), name='check_venta_descuento_lte_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'numero'), name='unique_venta_numero_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['venta'], name='idx_pago_venta'),
        ),
        migrations.AddIndex(
            model_name='pagoventa',
            index=models.Index(fields=['empresa', 'metodo_pago', 'fecha'], name='idx_pago_empresa_metodo_fecha'),
        ),
        migrations.AddConstraint(
            model_name='pagoventa',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='check_pago_monto_positivo'),
        ),
        migrations.AddIndex(
            model_name='lineaventa',
            index=models.Index(fields=['venta', 'orden'], name='idx_linea_venta_orden'),
        ),
        migrations.AddIndex(
            model_name='lineaventa',
            index=models.Index(fields=['empresa', 'producto', '-created_at'], name='idx_linvta_emp_prod'),
        ),
        migrations.AddConstraint(
            model_name='lineaventa',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='check_linea_venta_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='lineaventa',
            constraint=models.CheckConstraint(check=models.Q(('precio_unitario__gte', 0)), name='check_linea_venta_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='lineaventa',
            constraint=models.CheckConstraint(check=models.Q(('descuento__lte', django.db.models.expressions.CombinedExpression(models.F('precio_unitario'), '*', models.F('cantidad')))), name='check_linea_venta_descuento_lte_bruto'),
        ),
        migrations.AddConstraint(
            model_name='lineaventa',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='check_linea_venta_subtotal_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['venta'], name='idx_devolucion_venta'),
        ),
        migrations.AddIndex(
            model_name='devolucionventa',
            index=models.Index(fields=['empresa', 'fecha'], name='idx_devolucion_empresa_fecha'),
        ),
        migrations.AddConstraint(
            model_name='devolucionventa',
            constraint=models.CheckConstraint(check=models.Q(('total_devuelto__gte', 0)), name='check_devolucion_total_no_negativo'),
        ),
    ]
