# Generated by Django 5.0.6 on 2026-03-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numero',
            field=models.CharField(blank=True, help_text="Correlative reference number, e.g. 'V-2025-0001'. Set by VentaService.", max_length=20, null=True),
        ),
    ]
