# Generated by Django 5.0.6 on 2026-03-16 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_id', models.UUIDField(help_text='Unique identifier from the Event object', unique=True)),
                ('version', models.CharField(default='1.0', help_text='Event schema version', max_length=10)),
                ('usuario_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('FAILED_PERMANENT', 'Failed Permanent')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, help_text='Last error message if failed', null=True)),
            ],
            options={
                'verbose_name': 'Event Store',
                'verbose_name_plural': 'Event Store',
                'ordering': ['-created_at'],
            },
        ),
    ]
