# Generated by Django 5.0.6 on 2026-03-10 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_id', models.UUIDField(help_text='Unique identifier from the Event object', unique=True)),
                ('empresa_id', models.CharField(db_index=True, max_length=64)),
                ('usuario_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('FAILED_PERMANENT', 'Failed Permanent')], db_index=True, default='PENDING', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_log', models.TextField(blank=True, help_text='Last error message if failed', null=True)),
            ],
            options={
                'verbose_name': 'Event Store',
                'verbose_name_plural': 'Event Store',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='events_even_status_fcfe66_idx'), models.Index(fields=['event_name'], name='events_even_event_n_14547b_idx'), models.Index(fields=['created_at'], name='events_even_created_af76ba_idx'), models.Index(fields=['empresa_id', 'created_at'], name='events_even_empresa_262667_idx')],
            },
        ),
    ]
