# Generated by Django 5.0.6 on 2026-03-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstore',
            name='version',
            field=models.CharField(default='1.0', help_text='Event schema version', max_length=10),
        ),
    ]
