# Generated by Django 5.0.6 on 2026-03-13 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
        ('events', '0004_assign_default_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventstore',
            index=models.Index(fields=['empresa', 'status', '-created_at'], name='event_emp_stat_created_idx'),
        ),
    ]
