# Generated by Django 5.0.6 on 2026-03-16 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_anual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_usuarios', models.PositiveIntegerField(blank=True, null=True)),
                ('max_clientes', models.PositiveIntegerField(blank=True, null=True)),
                ('max_productos', models.PositiveIntegerField(blank=True, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ['precio_mensual'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('estado', models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('PENDING_PAYMENT', 'Pending Payment')], default='TRIAL', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('periodo_facturacion', models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('auto_renovar', models.BooleanField(default=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_provider', models.CharField(default='stripe', max_length=20)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='UsoMensual',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('mes', models.DateField(help_text='Primer día del mes (ej: 2026-03-01)')),
                ('usuarios_creados', models.PositiveIntegerField(default=0)),
                ('productos_creados', models.PositiveIntegerField(default=0)),
                ('ventas_creadas', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Uso Mensual',
                'verbose_name_plural': 'Usos Mensuales',
            },
        ),
    ]
