# Generated by Django 5.0.6 on 2026-03-13 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('empresas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='suscripcion',
            name='unique_active_subscription_per_empresa',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='limite_sucursales',
            new_name='max_clientes',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='limite_productos',
            new_name='max_productos',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='limite_usuarios',
            new_name='max_usuarios',
        ),
        migrations.RenameField(
            model_name='suscripcion',
            old_name='renovacion_automatica',
            new_name='auto_renovar',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='limite_ventas_mes',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='slug',
        ),
        migrations.AddField(
            model_name='plan',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='precio_anual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='periodo_facturacion',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled')], default='TRIAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='suscripcion',
            index=models.Index(fields=['empresa', 'estado', '-fecha_fin'], name='sub_emp_est_idx'),
        ),
        migrations.AddConstraint(
            model_name='suscripcion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['ACTIVE', 'TRIAL'])), fields=('empresa',), name='unique_active_sub_emp'),
        ),
    ]
