# Generated by Django 5.0.6 on 2026-03-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_suscripcion_unique_active_subscription_per_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='payment_provider',
            field=models.CharField(default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TRIAL', 'Trial'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('PENDING_PAYMENT', 'Pending Payment')], default='TRIAL', max_length=20),
        ),
    ]
