# Generated by Django 5.0.6 on 2026-03-09 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Amount intended to be paid.', max_digits=14)),
                ('moneda', models.CharField(default='ARS', help_text='ISO 4217 currency code (e.g., ARS, USD).', max_length=3)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('referencia_externa', models.CharField(blank=True, db_index=True, help_text='External transaction ID from Stripe, MercadoPago, etc.', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa')),
                ('metodo_pago', models.ForeignKey(help_text='The payment method used for this transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_transacciones', to='ventas.metodopago')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(help_text='The sale this payment belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_transacciones', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos_pago',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['empresa', 'venta'], name='pagos_pago_empresa_08b08e_idx'), models.Index(fields=['empresa', 'estado'], name='pagos_pago_empresa_b70f1e_idx'), models.Index(fields=['empresa', 'referencia_externa'], name='pagos_pago_empresa_1ce20c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='check_pagos_pago_monto_positivo'),
        ),
    ]
