# Generated by Django 5.0.6 on 2026-03-16 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('fecha_inicio', models.DateTimeField(help_text='Start of the blocked period (inclusive).')),
                ('fecha_fin', models.DateTimeField(help_text='End of the blocked period (exclusive).')),
                ('todo_el_dia', models.BooleanField(default=False, help_text='If True, the professional is blocked for all hours of every calendar day between fecha_inicio.date() and fecha_fin.date().')),
                ('motivo', models.CharField(blank=True, help_text="Optional reason: 'Holiday', 'Sick leave', 'Lunch break', etc.", max_length=200)),
            ],
            options={
                'verbose_name': 'Bloqueo de Horario',
                'verbose_name_plural': 'Bloqueos de Horario',
                'db_table': 'turnos_bloqueo_horario',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Day of the week (0=Monday … 6=Sunday).')),
                ('hora_inicio', models.TimeField(help_text='Start of working block, e.g. 09:00.')),
                ('hora_fin', models.TimeField(help_text='End of working block, e.g. 18:00.')),
                ('activo', models.BooleanField(default=True, help_text='Inactive schedules are ignored in availability checks. Useful for temporary suspensions without deletion.')),
            ],
            options={
                'verbose_name': 'Horario Disponible',
                'verbose_name_plural': 'Horarios Disponibles',
                'db_table': 'turnos_horario_disponible',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Contact email. Not used for login unless usuario is set.', max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True, help_text='Inactive professionals do not appear in booking flows.')),
                ('color_agenda', models.CharField(default='#10B981', help_text="Hex color for multi-staff calendar view, e.g. '#10B981'.", max_length=7)),
                ('notas_internas', models.TextField(blank=True, help_text='Internal notes about this professional. Not visible to clients.')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'db_table': 'turnos_profesional',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProfesionalServicio',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('duracion_override', models.PositiveIntegerField(blank=True, help_text='Override duration in minutes for this professional. NULL means use Servicio.duracion_minutos.', null=True)),
            ],
            options={
                'verbose_name': 'Servicio de Profesional',
                'verbose_name_plural': 'Servicios de Profesionales',
                'db_table': 'turnos_profesional_servicio',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(help_text='Display name shown to clients and staff.', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Optional longer description of what the service includes.')),
                ('duracion_minutos', models.PositiveIntegerField(help_text='Default duration in minutes. Used to auto-calculate Turno.fecha_fin.')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Catalog price. NULL = no fixed price (negotiated per appointment).', max_digits=10, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text="Hex color for calendar display, e.g. '#3B82F6'.", max_length=7)),
                ('activo', models.BooleanField(default=True, help_text='Inactive services cannot be booked but existing turnos are unaffected.')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'turnos_servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('fecha_inicio', models.DateTimeField(help_text='Appointment start time (user-provided).')),
                ('fecha_fin', models.DateTimeField(help_text='Appointment end time (calculated by service: fecha_inicio + effective_duration_minutes). Never set manually.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmación'), ('CONFIRMADO', 'Confirmado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('AUSENTE', 'Cliente ausente')], default='PENDIENTE', help_text='Current state in the appointment lifecycle.', max_length=20)),
                ('notas_internas', models.TextField(blank=True, help_text='Internal notes visible only to staff.')),
                ('notas_cliente', models.TextField(blank=True, help_text='Notes or special requests from the client.')),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, help_text='Price snapshot at booking time. NULL until confirmed. Defaults to Servicio.precio but may be adjusted per appointment.', max_digits=10, null=True)),
                ('cancelado_por', models.CharField(blank=True, choices=[('PROFESIONAL', 'Profesional'), ('CLIENTE', 'Cliente'), ('SISTEMA', 'Sistema (automático)')], help_text='Who cancelled the appointment. Required when estado=CANCELADO.', max_length=20, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, help_text='Free-text reason for cancellation.')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos_turno',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
