# Generated by Django 5.0.6 on 2026-03-09 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('empresas', '0002_initial'),
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueohorario',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloqueohorario',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='bloqueohorario',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horariodisponible',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horariodisponible',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='horariodisponible',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesional',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesional',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesional',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Platform account for this professional (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horariodisponible',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='turnos.profesional'),
        ),
        migrations.AddField(
            model_name='bloqueohorario',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='turnos.profesional'),
        ),
        migrations.AddField(
            model_name='profesionalservicio',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesionalservicio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='profesionalservicio',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_servicios', to='turnos.profesional'),
        ),
        migrations.AddField(
            model_name='profesionalservicio',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profesionalservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesional_servicios', to='turnos.servicio'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='profesionales', through='turnos.ProfesionalServicio', to='turnos.servicio'),
        ),
        migrations.AddField(
            model_name='turno',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Client receiving the service. NULL for walk-ins or internal blocks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='turno',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(help_text='Professional who will perform the service.', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.profesional'),
        ),
        migrations.AddField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(help_text='Service being performed.', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.servicio'),
        ),
        migrations.AddField(
            model_name='turno',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='horariodisponible',
            index=models.Index(fields=['empresa', 'profesional', 'dia_semana'], name='idx_hor_emp_prof_dia'),
        ),
        migrations.AddIndex(
            model_name='horariodisponible',
            index=models.Index(fields=['empresa', 'dia_semana', 'activo'], name='idx_horario_empresa_dia_activo'),
        ),
        migrations.AddConstraint(
            model_name='horariodisponible',
            constraint=models.CheckConstraint(check=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='check_horario_fin_despues_de_inicio'),
        ),
        migrations.AddIndex(
            model_name='bloqueohorario',
            index=models.Index(fields=['empresa', 'profesional', 'fecha_inicio'], name='idx_bloq_emp_prof_ini'),
        ),
        migrations.AddIndex(
            model_name='bloqueohorario',
            index=models.Index(fields=['empresa', 'profesional', 'fecha_fin'], name='idx_bloq_emp_prof_fin'),
        ),
        migrations.AddIndex(
            model_name='bloqueohorario',
            index=models.Index(fields=['empresa', 'fecha_inicio', 'fecha_fin'], name='idx_bloqueo_empresa_rango'),
        ),
        migrations.AddConstraint(
            model_name='bloqueohorario',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='check_bloqueo_fin_despues_de_inicio'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['empresa', 'activo'], name='idx_servicio_empresa_activo'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['empresa', 'nombre'], name='idx_servicio_empresa_nombre'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'nombre'), name='unique_servicio_nombre_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='servicio',
            constraint=models.CheckConstraint(check=models.Q(('duracion_minutos__gt', 0)), name='check_servicio_duracion_positiva'),
        ),
        migrations.AddIndex(
            model_name='profesionalservicio',
            index=models.Index(fields=['empresa', 'profesional'], name='idx_pserv_emp_prof'),
        ),
        migrations.AddIndex(
            model_name='profesionalservicio',
            index=models.Index(fields=['empresa', 'servicio'], name='idx_profserv_empresa_servicio'),
        ),
        migrations.AddConstraint(
            model_name='profesionalservicio',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'profesional', 'servicio'), name='unique_profesional_servicio_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='profesionalservicio',
            constraint=models.CheckConstraint(check=models.Q(('duracion_override__isnull', True), ('duracion_override__gt', 0), _connector='OR'), name='check_profesional_servicio_duracion_override_positiva'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['empresa', 'activo'], name='idx_profesional_empresa_activo'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['empresa', 'usuario'], name='idx_prof_emp_user'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['empresa', 'apellido', 'nombre'], name='idx_profesional_empresa_nombre'),
        ),
        migrations.AddConstraint(
            model_name='profesional',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('usuario__isnull', False)), fields=('empresa', 'usuario'), name='unique_profesional_usuario_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empresa', 'profesional', 'fecha_inicio'], name='idx_trn_emp_prof_ini'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empresa', 'profesional', 'estado', 'fecha_inicio'], name='idx_trn_emp_prof_est'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empresa', 'profesional', 'fecha_fin'], name='idx_trn_emp_prof_fin'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empresa', 'cliente', 'fecha_inicio'], name='idx_trn_emp_cli_ini'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empresa', 'fecha_inicio'], name='idx_turno_empresa_inicio'),
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['empresa', 'estado'], name='idx_turno_empresa_estado'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(check=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='check_turno_fin_despues_de_inicio'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('estado', 'CANCELADO'), _negated=True), ('cancelado_por__isnull', False), _connector='OR'), name='check_turno_cancelado_requiere_actor'),
        ),
    ]
