# Generated by Django 5.0.6 on 2026-03-16 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Amount intended to be paid.', max_digits=14)),
                ('moneda', models.CharField(default='ARS', help_text='ISO 4217 currency code (e.g., ARS, USD).', max_length=3)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], db_index=True, default='PENDIENTE', max_length=20)),
                ('referencia_externa', models.CharField(blank=True, db_index=True, help_text='External transaction ID from Stripe, MercadoPago, etc.', max_length=100)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos_pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
