# Generated by Django 5.0.6 on 2026-03-16 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranzas', '0001_initial'),
        ('empresas', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.ForeignKey(help_text='The payment method used for this transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_transacciones', to='ventas.metodopago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(help_text='The sale this payment belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='pagos_transacciones', to='ventas.venta'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['empresa', 'venta'], name='pagos_pago_empresa_08b08e_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['empresa', 'estado'], name='pagos_pago_empresa_b70f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['empresa', 'referencia_externa'], name='pagos_pago_empresa_1ce20c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(check=models.Q(('monto__gt', 0)), name='check_pagos_pago_monto_positivo'),
        ),
    ]
