# Generated by Django 5.0.6 on 2026-03-09 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL identifier, e.g. 'mi-empresa'. Auto-generated from nombre.", max_length=100, unique=True)),
                ('email', models.EmailField(help_text='Primary contact email.', max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive empresas cannot access the API.')),
                ('logo_url', models.URLField(blank=True)),
                ('zona_horaria', models.CharField(default='America/Argentina/Buenos_Aires', max_length=50)),
                ('pais', models.CharField(default='ARG', max_length=3)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas_empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaConfiguracion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('color_primario', models.CharField(default='#3B82F6', max_length=7)),
                ('color_secundario', models.CharField(default='#1E40AF', max_length=7)),
                ('duracion_turno_default', models.PositiveIntegerField(default=30, help_text='Default appointment duration in minutes.')),
                ('recordatorio_horas_antes', models.PositiveIntegerField(default=24, help_text='Hours before appointment to send reminder.')),
                ('permite_cancelacion_horas', models.PositiveIntegerField(default=2, help_text='Minimum hours before appointment to allow cancellation.')),
                ('moneda', models.CharField(default='ARS', max_length=3)),
                ('prefijo_factura', models.CharField(default='FAC', max_length=10)),
                ('punto_venta_afip', models.PositiveIntegerField(blank=True, null=True)),
                ('google_calendar_token', models.TextField(blank=True)),
                ('whatsapp_token', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'db_table': 'empresas_configuracion',
            },
        ),
    ]
