# Generated by Django 5.0.6 on 2026-03-12 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
        ('facturacion', '0002_factura_numero_secuencial_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineafactura',
            options={'verbose_name': 'Línea de Factura', 'verbose_name_plural': 'Líneas de Factura'},
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='empresa',
            field=models.ForeignKey(default='b27a8d27-4014-4912-8098-71fa5b9d7e96', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lineafactura',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
