# Generated by Django 5.0.6 on 2026-03-16 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Quick internal notes. Use NotaCliente for structured notes.')),
                ('activo', models.BooleanField(default=True, help_text='Inactive clients are hidden from default lists but not deleted.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra data: external IDs, custom fields, etc.')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes_cliente',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ClienteEtiqueta',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
            ],
            options={
                'verbose_name': 'Etiqueta de Cliente',
                'verbose_name_plural': 'Etiquetas de Clientes',
                'db_table': 'clientes_cliente_etiqueta',
            },
        ),
        migrations.CreateModel(
            name='EtiquetaCliente',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6B7280', help_text="Hex color code, e.g. '#3B82F6'.", max_length=7)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'db_table': 'clientes_etiqueta',
            },
        ),
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('tipo_evento', models.CharField(choices=[('CREATED', 'Cliente creado'), ('UPDATED', 'Cliente actualizado'), ('TAG_ADDED', 'Etiqueta agregada'), ('TAG_REMOVED', 'Etiqueta removida'), ('NOTE_ADDED', 'Nota agregada'), ('NOTE_DELETED', 'Nota eliminada'), ('ACTIVATED', 'Cliente activado'), ('DEACTIVATED', 'Cliente desactivado'), ('DELETED', 'Cliente eliminado'), ('RESTORED', 'Cliente restaurado')], db_index=True, max_length=20)),
                ('descripcion', models.CharField(help_text='Human-readable description of what happened.', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Event-specific context (e.g. changed fields, tag name).')),
            ],
            options={
                'verbose_name': 'Historial de Cliente',
                'verbose_name_plural': 'Historial de Clientes',
                'db_table': 'clientes_historial',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotaCliente',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp. NULL means record is active.', null=True)),
                ('contenido', models.TextField()),
            ],
            options={
                'verbose_name': 'Nota de Cliente',
                'verbose_name_plural': 'Notas de Clientes',
                'db_table': 'clientes_nota',
                'ordering': ['-created_at'],
            },
        ),
    ]
