# Generated by Django 5.0.6 on 2026-03-16 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienteetiqueta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_etiquetas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='clienteetiqueta',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienteetiqueta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='clienteetiqueta',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etiquetacliente',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='etiquetacliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='etiquetacliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clienteetiqueta',
            name='etiqueta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_etiquetas', to='clientes.etiquetacliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='clientes', through='clientes.ClienteEtiqueta', to='clientes.etiquetacliente'),
        ),
        migrations.AddField(
            model_name='historialcliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='historialcliente',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialcliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='historialcliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_detalle', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='notacliente',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notacliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='notacliente',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='etiquetacliente',
            index=models.Index(fields=['empresa', 'nombre'], name='clientes_et_empresa_aff635_idx'),
        ),
        migrations.AddConstraint(
            model_name='etiquetacliente',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('empresa', 'nombre'), name='unique_etiqueta_nombre_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='clienteetiqueta',
            index=models.Index(fields=['empresa', 'cliente'], name='clientes_cl_empresa_b77d69_idx'),
        ),
        migrations.AddIndex(
            model_name='clienteetiqueta',
            index=models.Index(fields=['empresa', 'etiqueta'], name='clientes_cl_empresa_0d93b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='clienteetiqueta',
            constraint=models.UniqueConstraint(fields=('empresa', 'cliente', 'etiqueta'), name='unique_cliente_etiqueta_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'activo'], name='idx_cliente_empresa_activo'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'email'], name='idx_cliente_empresa_email'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'telefono'], name='idx_cliente_empresa_telefono'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'apellido', 'nombre'], name='idx_cliente_empresa_nombre'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('email__gt', '')), fields=('empresa', 'email'), name='unique_cliente_email_por_empresa'),
        ),
        migrations.AddIndex(
            model_name='historialcliente',
            index=models.Index(fields=['empresa', 'cliente'], name='clientes_hi_empresa_63634f_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcliente',
            index=models.Index(fields=['empresa', 'tipo_evento'], name='clientes_hi_empresa_3c82dc_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcliente',
            index=models.Index(fields=['empresa', 'cliente', 'created_at'], name='clientes_hi_empresa_eb17b7_idx'),
        ),
        migrations.AddIndex(
            model_name='notacliente',
            index=models.Index(fields=['empresa', 'cliente'], name='clientes_no_empresa_c16b96_idx'),
        ),
        migrations.AddIndex(
            model_name='notacliente',
            index=models.Index(fields=['empresa', 'created_at'], name='clientes_no_empresa_7ef3d3_idx'),
        ),
    ]
