# Generated by Django 5.0.6 on 2026-03-16 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditlog', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='empresas.empresa'),
        ),
    ]
